---
abstract: 'Qooxdoo JSON-RPC support for the Mojolicious Perl framework'
author:
  - 'Tobias Oetiker <tobi@oetiker.ch>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.88, CPAN::Meta::Converter version 2.120351'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojolicious-Plugin-Qooxdoo
no_index:
  directory:
    - t
    - inc
    - t
    - example
    - setup
requires:
  Mojolicious: 4.0
  perl: 5.010001
resources:
  bugtracker: https://github.com/oetiker/Mojolicious-Plugin-Qooxdoo/issues
  license: http://www.opensource.org/licenses/artistic-license-2.0
  repository: https://github.com/oetiker/Mojolicious-Plugin-Qooxdoo
version: 0.4
