--- #YAML:1.0
name:               Mojolicious-Plugin-Qooxdoo
version:            0.1
abstract:           Qooxdoo JSON-RPC support for the Mojolicious Perl framework
author:
    - Tobias Oetiker <tobi@oetiker.ch>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  6.31
build_requires:
    Test::More:  0
requires:
    Mojolicious:  4.0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
